import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
entry_key.c
reg_key_fp.c
reg_key_rc.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
